@echo off
REM ---------------------------------------------------------------------------
REM Make the Barrier client start at login and stay connected, with no window
REM and no clicking.
REM
REM     install-windows-autostart.bat <mac-ip>
REM     install-windows-autostart.bat 192.168.3.79
REM
REM What this does:
REM   1. Copies barrierc.exe and its DLLs to %LOCALAPPDATA%\Barrier\bin, so
REM      autostart keeps working if you move or rebuild the repo.
REM   2. Writes a small launcher script that runs the client with no console
REM      window and relaunches it if it ever exits.
REM   3. Puts that launcher in your Startup folder.
REM   4. Starts it now, so you do not have to log out first.
REM
REM This runs as YOU, at login, in your own session. It does not install a
REM service and does not need administrator rights. The background service this
REM project used to install ran as LocalSystem and took commands over an
REM unauthenticated local socket, which let any local user run code as SYSTEM;
REM it has been removed.
REM
REM Trade-off worth knowing: because this runs in your session, the MacBook
REM keyboard works once you are logged in, but NOT on the Windows lock screen or
REM sign-in screen, and not over UAC prompts. Use the PC's own keyboard to log
REM in; Barrier takes over immediately afterwards.
REM
REM To undo: remove-windows-autostart.bat
REM ---------------------------------------------------------------------------

setlocal

set "SERVER=%~1"
if "%SERVER%"=="" (
    echo.
    echo Usage: install-windows-autostart.bat ^<mac-ip^>
    echo.
    echo Example:
    echo     install-windows-autostart.bat 192.168.3.79
    echo.
    echo That is the MacBook's address. On the Mac, find it with:
    echo     ipconfig getifaddr en0
    echo.
    exit /b 1
)

set "SCREENNAME=windows"
set "SRC=%~dp0build\bin\Release"
set "DEST=%LOCALAPPDATA%\Barrier\bin"
set "VBS=%LOCALAPPDATA%\Barrier\start-barrier-client.vbs"
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "LINK=%STARTUP%\Barrier Client.vbs"

if not exist "%SRC%\barrierc.exe" (
    echo.
    echo ERROR: %SRC%\barrierc.exe not found.
    echo.
    echo Build it first, from an "x64 Native Tools Command Prompt for VS":
    echo     build-windows-client.bat
    echo.
    exit /b 1
)

echo Installing Barrier client autostart
echo   server:      %SERVER%
echo   screen name: %SCREENNAME%
echo.

REM --- 1. copy the binary somewhere stable -------------------------------------
if not exist "%DEST%" mkdir "%DEST%" >NUL 2>&1
copy /Y "%SRC%\barrierc.exe" "%DEST%\" >NUL
if errorlevel 1 (
    echo ERROR: could not copy barrierc.exe to %DEST%
    exit /b 1
)
copy /Y "%SRC%\*.dll" "%DEST%\" >NUL 2>&1
echo Copied client to %DEST%

REM --- 2. write the launcher ---------------------------------------------------
REM Window style 0 means no console window. The loop relaunches the client if it
REM exits; the client handles a missing or restarting server by itself, retrying
REM about once a second, so this only matters if the process actually dies.
>"%VBS%" echo ' Starts the Barrier client hidden and keeps it running.
>>"%VBS%" echo ' Generated by install-windows-autostart.bat -- edit the server
>>"%VBS%" echo ' address below, or just re-run that script with a new address.
>>"%VBS%" echo cmd = """%DEST%\barrierc.exe"" --name %SCREENNAME% %SERVER%"
>>"%VBS%" echo Set sh = CreateObject("WScript.Shell")
>>"%VBS%" echo Do
>>"%VBS%" echo     sh.Run cmd, 0, True
>>"%VBS%" echo     WScript.Sleep 5000
>>"%VBS%" echo Loop

if not exist "%VBS%" (
    echo ERROR: could not write launcher to %VBS%
    exit /b 1
)
echo Wrote launcher to %VBS%

REM --- 3. run it at login ------------------------------------------------------
if not exist "%STARTUP%" mkdir "%STARTUP%" >NUL 2>&1
copy /Y "%VBS%" "%LINK%" >NUL
if errorlevel 1 (
    echo ERROR: could not install into the Startup folder:
    echo   %STARTUP%
    exit /b 1
)
echo Installed into Startup

REM --- 4. start it now ---------------------------------------------------------
taskkill /f /im barrierc.exe >NUL 2>&1
start "" wscript.exe "%VBS%"

echo.
echo ============================================================
echo  Done. The Barrier client is running now and will start
echo  automatically every time you log in. No window, no clicks.
echo.
echo  It retries about once a second, so it connects on its own
echo  whenever the MacBook server comes up.
echo.
echo  If this is the first time, the connection will be REFUSED
echo  until the two machines have exchanged fingerprints.
echo  See doc\WINDOWS-CLIENT.md step 6.
echo.
echo  Check it is running:   tasklist ^| findstr barrierc
echo  Stop and uninstall:    remove-windows-autostart.bat
echo ============================================================
echo.

endlocal
